apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
  namespace: mba
spec:
  containers:
    - resources:
      image: mysql:5.6
      name : mysql
      env :
        - name : MYSQL_ROOT_PASSWORD
          value : root
      ports :
        - containerPort : 3306
